name: Test Script

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Random File
        shell: pwsh
        run: |
          New-Item -Path 'artifacts' -ItemType Directory -Force
          New-Item -Path 'artifacts\test.txt' -ItemType File -Force
  deploy:
    name: Publish R2
    needs: build
    uses: OxideMod/Actions/.github/workflows/r2-publish.yml@main
    with:
      key: ${{ secrets.KEY }}
      secret: ${{ secrets.SECRET }}
      endpoint: ${{ secrets.URL }}
