name: Test Script

on: [workflow_dispatch]

jobs:
  build:
    name: Run Blue Build
    uses: MrBlue/Oxide.Rust/.github/workflows/build.yaml@develop
    secrets: inherit
    with:
      branch-postfix: "-develop"