name: Test Script

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Random File
        shell: pwsh
        run: |
          New-Item -Path 'artifacts' -ItemType Directory -Force
          New-Item -Path 'artifacts\test.txt' -ItemType File -Force
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: artifacts
  deploy:
    name: Publish Files
    uses: OxideMod/Actions/.github/workflows/r2-publish.yml@main
    secrets: inherit
