name: Test Script

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Random File
        shell: pwsh
        run: |
          New-Item -Path 'artifacts' -ItemType Directory -Force
          New-Item -Path 'artifacts\test.txt' -ItemType File -Force
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: artifacts
  deploy:
    name: Publish Files
    needs: build
    uses: OxideMod/Actions/.github/workflows/r2-publish.yml@main
    secrets:
      CLOUDFLARE_R2_KEY: ${{ secrets.CLOUDFLARE_R2_KEY }}
      CLOUDFLARE_R2_SECRET: ${{ secrets.CLOUDFLARE_R2_SECRET }}
      CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
